---
functional:
  - Пользователь должен иметь возможность создавать сам игры и ждать соперника
  - Пользователь должен иметь возможность вступать в открытые игры
  - Пользователь должен иметь возможность зайти в запущенную игру в качестве зрителя
  - Пользователь должен иметь возможность пригласить по ссылке кого-то конкретного в игру
  - Пользователь должен иметь возможность авторизации через github/discord
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей
implicit:
  - Пользователь должен иметь возможность авторизации/регистрации на сайте
  - Пользователь должен иметь возможность просматривать таблицу лидеров 
  - Пользователь должен иметь возможность просматривать историю турниров
  - Пользователь должен иметь возможность просматривать историю игр всех пользователей на сайте
  - Пользователь должен иметь возможность просматривать рейтинг всех пользователей 
  - Пользователь должен иметь возможность просматривать свой личный кабинет на сайте
  - Пользователь должен иметь возможность выбирать конкретную задачу при создании батла
  - Пользователь должен иметь возможность выбирать уровень сложности при создании батла
  - Пользователь должен иметь возможность сдаться 
  - Пользователь должен иметь возможность создавать новые задачи
