---
functional:
  - Пользователь должен иметь возможность создавать сам игры и ждать соперника
  - Пользователь должен иметь возможность создавать игры против ботов
  - Пользователь должен иметь возможность вступать в открытые игры
  - Пользователь должен иметь возможность зайти в запущенную игру в качестве зрителя
  - Пользователь должен иметь возможность пригласить по ссылке кого-то конкретного в игру
  - Пользователь должен иметь возможность авторизации через github/discord
  - Пользователь должен иметь возможность провести тестовый батл без регистрации/авторизации
  - Пользователь должен иметь возможность создавать турнир
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей
implicit:
  - Пользователь должен иметь возможность авторизации/регистрации на сайте
  - Пользователь должен получить сообщение об ошибке при вводе невалидных данных при регистрации
  - При вводе неправильного логина/пароля пользователь должен получить сообщение об ошибке
  - При верном вводе логина и пароля пользователь должен войти в систему
  - Пользователь должен иметь возможность открыть профиль любого другого пользователя
  - Пользователь не может отправить приглашение несуществующему игроку
  - Пользователь не может зарегистрировать несколько аккаунтов на одну почту
  - Пользователь должен иметь возможность смены никнейма
  - Пользователь должен иметь возможность смены пароля
  - Пользователь должен иметь возможность просматривать список онлайн-игроков по клику из баннера
  - Пользователь должен иметь возможность просматривать таблицу лидеров по критериям
  - Пользователь должен иметь возможность просматривать историю турниров
  - Пользователь должен иметь возможность пригласить друга в игру
  - Пользователь должен иметь возможность просматривать историю игр всех пользователей на сайте
  - Пользователь должен иметь возможность сортировать пользователей по заданным критериям на странице рейтинга
  - Пользователь должен иметь возможность просматривать свой личный кабинет на сайте
  - Пользователь должен иметь возможность выбирать конкретную задачу при создании батла
  - Пользователь должен иметь возможность выбирать уровень сложности при создании батла
  - Пользователь должен иметь возможность сдаться в батле
  - Пользователь должен иметь возможность создавать новые задачи
  - Пользователь должен иметь возможность отправлять приватные сообщения
